language: go

install:
  - go get github.com/axamon/q

script:
 # - go test -cover $(go list ./... | grep -v /vendor/ | grep -v /build/) -v
  - ./test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)